version: '2'
services:
  web:
    image: alxshelepenok/gatsby-starter-lumen:development
    build:
      context: ./
      dockerfile: Dockerfile.development
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - "9000:9000"
